/**
 * Curriculum Vocabulary & Mission Briefings for BaseScrib
 * Synchronized with BaseScrib/Back/populate_vocabulary.py
 */

export const CURRICULUM_VOCABULARY_DATA = {
  1: [
    { en: "name", es: "nombre", category: "personal" },
    { en: "age", es: "edad", category: "personal" },
    { en: "country", es: "país", category: "personal" },
    { en: "favorite", es: "favorito", category: "personal" },
    { en: "like", es: "gustar", category: "actions" },
    { en: "can", es: "poder", category: "actions" },
    { en: "fly", es: "volar", category: "actions" },
    { en: "repair", es: "reparar", category: "actions" },
    { en: "introduce yourself", es: "preséntate", category: "actions" },
    { en: "dance", es: "bailar", category: "actions" },
    { en: "play sports", es: "hacer deportes", category: "actions" },
    { en: "make handicrafts", es: "hacer manualidades", category: "actions" },
    { en: "sing", es: "cantar", category: "actions" },
    { en: "cook", es: "cocinar", category: "actions" }
  ],
  2: [
    { en: "robot", es: "robot", category: "technology" },
    { en: "table", es: "mesa", category: "furniture" },
    { en: "chair", es: "silla", category: "furniture" },
    { en: "book", es: "libro", category: "objects" },
    { en: "computer", es: "computadora", category: "technology" },
    { en: "photo", es: "foto", category: "objects" },
    { en: "bed", es: "cama", category: "furniture" },
    { en: "room", es: "cuarto / sala", category: "places" },
    { en: "screen", es: "pantalla", category: "technology" },
    { en: "garden", es: "jardín", category: "places" },
    { en: "shelf", es: "estante", category: "furniture" },
    { en: "help", es: "ayudar", category: "actions" }
  ],
  3: [
    { en: "wake up", es: "despertarse", category: "routines" },
    { en: "study", es: "estudiar", category: "routines" },
    { en: "clean", es: "limpiar", category: "routines" },
    { en: "eat", es: "comer", category: "routines" },
    { en: "write", es: "escribir", category: "routines" },
    { en: "sleep", es: "dormir", category: "routines" },
    { en: "schedule", es: "horario", category: "routines" },
    { en: "have breakfast", es: "desayunar", category: "routines" },
    { en: "have lunch", es: "almorzar", category: "routines" },
    { en: "have dinner", es: "cenar", category: "routines" },
    { en: "take a shower", es: "bañarse", category: "routines" },
    { en: "get dressed", es: "vestirse", category: "routines" }
  ],
  4: [
    { en: "sick", es: "enfermo", category: "states" },
    { en: "studying", es: "estudiando", category: "actions" },
    { en: "cleaning", es: "limpiando", category: "actions" },
    { en: "reading", es: "leyendo", category: "actions" },
    { en: "writing", es: "escribiendo", category: "actions" },
    { en: "eating", es: "comiendo", category: "actions" },
    { en: "talking", es: "conversando", category: "actions" },
    { en: "working", es: "trabajando", category: "actions" },
    { en: "drawing", es: "dibujando", category: "actions" },
    { en: "resting", es: "descansando", category: "actions" },
    { en: "listening to", es: "escuchando", category: "actions" },
    { en: "cooking", es: "cocinando", category: "actions" }
  ],
  5: [
    { en: "always", es: "siempre", category: "frequency" },
    { en: "sometimes", es: "a veces", category: "frequency" },
    { en: "never", es: "nunca", category: "frequency" },
    { en: "usually", es: "usualmente", category: "frequency" },
    { en: "rarely", es: "raramente", category: "frequency" },
    { en: "often", es: "a menudo", category: "frequency" },
    { en: "daily", es: "a diario", category: "frequency" },
    { en: "weekly", es: "semanalmente", category: "frequency" },
    { en: "monthly", es: "mensualmente", category: "frequency" },
    { en: "seldom", es: "casi nunca", category: "frequency" },
    { en: "frequently", es: "frecuentemente", category: "frequency" },
    { en: "schedule", es: "horario", category: "time" },
    { en: "time", es: "tiempo / hora", category: "time" },
    { en: "checklist", es: "lista de control", category: "objects" },
    { en: "drill", es: "simulacro", category: "actions" },
    { en: "protocol", es: "protocolo", category: "general" },
    { en: "inspection", es: "inspección", category: "general" },
    { en: "timeline", es: "cronograma", category: "time" },
    { en: "punctual", es: "puntual", category: "adjectives" },
    { en: "practice", es: "practicar", category: "actions" },
    { en: "workout", es: "entrenamiento físico", category: "actions" },
    { en: "help", es: "ayudar", category: "actions" },
    { en: "meet", es: "reunirse", category: "actions" },
    { en: "explore", es: "explorar", category: "actions" },
    { en: "reminder", es: "recordatorio", category: "objects" }
  ],
  6: [
    { en: "have", es: "tener", category: "verbs" },
    { en: "has", es: "tener (él/ella)", category: "verbs" },
    { en: "don't have", es: "no tener", category: "verbs" },
    { en: "toolkit", es: "caja de herramientas", category: "equipment" },
    { en: "oxygen tank", es: "tanque de oxígeno", category: "equipment" },
    { en: "scanner", es: "escáner", category: "equipment" },
    { en: "energy cell", es: "célula de energía", category: "equipment" },
    { en: "key code", es: "código de acceso", category: "security" },
    { en: "laser torch", es: "antorcha láser", category: "equipment" },
    { en: "multi-tool", es: "multiherramienta", category: "equipment" },
    { en: "power core", es: "núcleo de poder", category: "equipment" },
    { en: "battery pack", es: "paquete de baterías", category: "equipment" },
    { en: "probe", es: "sonda espacial", category: "equipment" },
    { en: "transceiver", es: "transceptor", category: "equipment" },
    { en: "fuse", es: "fusible", category: "equipment" },
    { en: "circuit", es: "circuito", category: "equipment" },
    { en: "wrench", es: "llave inglesa", category: "equipment" },
    { en: "generator", es: "generador", category: "equipment" },
    { en: "harness", es: "arnés", category: "equipment" },
    { en: "connector", es: "conector", category: "equipment" },
    { en: "display", es: "pantalla", category: "equipment" },
    { en: "spare", es: "repuesto", category: "equipment" },
    { en: "gear", es: "equipo / engranaje", category: "equipment" },
    { en: "gadget", es: "dispositivo", category: "equipment" },
    { en: "supplies", es: "suministros", category: "equipment" }
  ],
  7: [
    { en: "what", es: "qué / cuál", category: "questions" },
    { en: "where", es: "dónde", category: "questions" },
    { en: "when", es: "cuándo", category: "questions" },
    { en: "who", es: "quién", category: "questions" },
    { en: "why", es: "por qué", category: "questions" },
    { en: "how", es: "cómo", category: "questions" },
    { en: "which", es: "cuál (opción)", category: "questions" },
    { en: "whose", es: "de quién", category: "questions" },
    { en: "signal", es: "señal", category: "communication" },
    { en: "frequency", es: "frecuencia", category: "communication" },
    { en: "anomaly", es: "anomalía", category: "science" },
    { en: "origin", es: "origen", category: "navigation" },
    { en: "destination", es: "destino", category: "navigation" },
    { en: "location", es: "ubicación", category: "navigation" },
    { en: "query", es: "consulta", category: "communication" },
    { en: "answer", es: "respuesta", category: "communication" },
    { en: "reason", es: "razón / motivo", category: "general" },
    { en: "trajectory", es: "trayectoria", category: "navigation" },
    { en: "distance", es: "distancia", category: "navigation" },
    { en: "speed", es: "velocidad", category: "physics" },
    { en: "target", es: "objetivo", category: "navigation" },
    { en: "beacon", es: "baliza", category: "technology" },
    { en: "transmission", es: "transmisión", category: "communication" },
    { en: "transmitter", es: "transmisor", category: "communication" },
    { en: "status", es: "estado", category: "general" }
  ],
  8: [
    { en: "my", es: "mi", category: "possessives" },
    { en: "your", es: "tu", category: "possessives" },
    { en: "his", es: "su (de él)", category: "possessives" },
    { en: "her", es: "su (de ella)", category: "possessives" },
    { en: "our", es: "nuestro", category: "possessives" },
    { en: "their", es: "su (de ellos)", category: "possessives" },
    { en: "mine", es: "mío", category: "possessives" },
    { en: "yours", es: "tuyo", category: "possessives" },
    { en: "hers", es: "suyo (de ella)", category: "possessives" },
    { en: "ours", es: "nuestro (pronombre)", category: "possessives" },
    { en: "theirs", es: "de ellos (pronombre)", category: "possessives" },
    { en: "visor", es: "visor", category: "equipment" },
    { en: "badge", es: "insignia", category: "equipment" },
    { en: "datapad", es: "tableta de datos", category: "equipment" },
    { en: "backpack", es: "mochila", category: "equipment" },
    { en: "insignia", es: "distintivo", category: "equipment" },
    { en: "tag", es: "etiqueta", category: "equipment" },
    { en: "credentials", es: "credenciales", category: "security" },
    { en: "token", es: "ficha / pase", category: "security" },
    { en: "emblem", es: "emblema", category: "equipment" },
    { en: "belongings", es: "pertenencias", category: "general" },
    { en: "locker", es: "casillero", category: "furniture" },
    { en: "identity", es: "identidad", category: "personal" },
    { en: "keycard", es: "tarjeta llave", category: "security" },
    { en: "uniform", es: "uniforme", category: "clothing" }
  ],
  9: [
    { en: "me", es: "mí / me", category: "pronouns" },
    { en: "him", es: "él / lo", category: "pronouns" },
    { en: "her", es: "ella / la", category: "pronouns" },
    { en: "us", es: "nosotros / nos", category: "pronouns" },
    { en: "them", es: "ellos / los", category: "pronouns" },
    { en: "transmission", es: "transmisión", category: "communication" },
    { en: "channel", es: "canal", category: "communication" },
    { en: "coordinates", es: "coordenadas", category: "navigation" },
    { en: "message", es: "mensaje", category: "communication" },
    { en: "dispatcher", es: "despachador", category: "people" },
    { en: "receiver", es: "receptor", category: "equipment" },
    { en: "sender", es: "remitente", category: "people" },
    { en: "audio", es: "audio", category: "media" },
    { en: "frequency", es: "frecuencia", category: "communication" },
    { en: "uplink", es: "enlace de subida", category: "communication" },
    { en: "downlink", es: "enlace de bajada", category: "communication" },
    { en: "satellite", es: "satélite", category: "space" },
    { en: "relay", es: "repetidor", category: "technology" },
    { en: "antenna", es: "antena", category: "technology" },
    { en: "broadcast", es: "difusión", category: "communication" },
    { en: "intercom", es: "intercomunicador", category: "technology" },
    { en: "ping", es: "pulso de señal", category: "technology" },
    { en: "wavelength", es: "longitud de onda", category: "physics" },
    { en: "listen", es: "escuchar", category: "actions" },
    { en: "send", es: "enviar", category: "actions" }
  ],
  10: [
    { en: "this", es: "este / esta", category: "demonstratives" },
    { en: "that", es: "ese / esa / aquel", category: "demonstratives" },
    { en: "these", es: "estos / estas", category: "demonstratives" },
    { en: "those", es: "esos / esas", category: "demonstratives" },
    { en: "shield", es: "escudo", category: "technology" },
    { en: "console", es: "consola", category: "technology" },
    { en: "controls", es: "controles", category: "technology" },
    { en: "deck", es: "cubierta", category: "places" },
    { en: "terminal", es: "terminal", category: "technology" },
    { en: "switch", es: "interruptor", category: "technology" },
    { en: "lever", es: "palanca", category: "technology" },
    { en: "dashboard", es: "panel de control", category: "technology" },
    { en: "indicator", es: "indicador", category: "technology" },
    { en: "gauge", es: "manómetro / medidor", category: "technology" },
    { en: "dial", es: "cuadrante", category: "technology" },
    { en: "screen", es: "pantalla", category: "technology" },
    { en: "panel", es: "panel", category: "technology" },
    { en: "keyboard", es: "teclado", category: "technology" },
    { en: "interface", es: "interfaz", category: "technology" },
    { en: "mechanism", es: "mecanismo", category: "technology" },
    { en: "unit", es: "unidad", category: "technology" },
    { en: "mainframe", es: "servidor central", category: "technology" },
    { en: "apparatus", es: "aparato", category: "technology" },
    { en: "cyberdeck", es: "ciberconsola", category: "technology" },
    { en: "system", es: "sistema", category: "technology" }
  ],
  11: [
    { en: "faster", es: "más rápido", category: "comparatives" },
    { en: "bigger", es: "más grande", category: "comparatives" },
    { en: "smaller", es: "más pequeño", category: "comparatives" },
    { en: "brighter", es: "más brillante", category: "comparatives" },
    { en: "stronger", es: "más fuerte", category: "comparatives" },
    { en: "colder", es: "más frío", category: "comparatives" },
    { en: "warmer", es: "más cálido", category: "comparatives" },
    { en: "closer", es: "más cercano", category: "comparatives" },
    { en: "heavier", es: "más pesado", category: "comparatives" },
    { en: "lighter", es: "más liviano", category: "comparatives" },
    { en: "farther", es: "más lejos", category: "comparatives" },
    { en: "nearer", es: "más cerca", category: "comparatives" },
    { en: "higher", es: "más alto", category: "comparatives" },
    { en: "deeper", es: "más profundo", category: "comparatives" },
    { en: "safer", es: "más seguro", category: "comparatives" },
    { en: "better", es: "mejor", category: "comparatives" },
    { en: "worse", es: "peor", category: "comparatives" },
    { en: "explorer", es: "explorador", category: "people" },
    { en: "speed", es: "velocidad", category: "physics" },
    { en: "propulsion", es: "propulsión", category: "technology" },
    { en: "thrust", es: "empuje", category: "physics" },
    { en: "engine", es: "motor", category: "technology" },
    { en: "booster", es: "propulsor", category: "technology" },
    { en: "starship", es: "astronave", category: "vehicles" },
    { en: "altitude", es: "altitud", category: "physics" }
  ],
  12: [
    { en: "fastest", es: "el más rápido", category: "superlatives" },
    { en: "brightest", es: "el más brillante", category: "superlatives" },
    { en: "biggest", es: "el más grande", category: "superlatives" },
    { en: "smallest", es: "el más pequeño", category: "superlatives" },
    { en: "furthest", es: "el más lejano", category: "superlatives" },
    { en: "deepest", es: "el más profundo", category: "superlatives" },
    { en: "safest", es: "el más seguro", category: "superlatives" },
    { en: "oldest", es: "el más antiguo", category: "superlatives" },
    { en: "newest", es: "el más nuevo", category: "superlatives" },
    { en: "greatest", es: "el más grandioso", category: "superlatives" },
    { en: "highest", es: "el más alto", category: "superlatives" },
    { en: "coldest", es: "el más frío", category: "superlatives" },
    { en: "record", es: "récord", category: "general" },
    { en: "champion", es: "campeón", category: "people" },
    { en: "peak", es: "cima / cúspide", category: "places" },
    { en: "nebula", es: "nebulosa", category: "space" },
    { en: "supernova", es: "supernova", category: "space" },
    { en: "black hole", es: "agujero negro", category: "space" },
    { en: "cosmos", es: "cosmos", category: "space" },
    { en: "quasar", es: "cuásar", category: "space" },
    { en: "asteroid", es: "asteroide", category: "space" },
    { en: "comet", es: "cometa", category: "space" },
    { en: "zenith", es: "cénit", category: "space" },
    { en: "cluster", es: "cúmulo estelar", category: "space" },
    { en: "infinity", es: "infinito", category: "space" }
  ],
  13: [
    { en: "visited", es: "visitó / visitado", category: "past" },
    { en: "landed", es: "aterrizó", category: "past" },
    { en: "launched", es: "lanzó / despegó", category: "past" },
    { en: "discovered", es: "descubrió", category: "past" },
    { en: "traveled", es: "viajó", category: "past" },
    { en: "repaired", es: "reparó", category: "past" },
    { en: "transmitted", es: "transmitió", category: "past" },
    { en: "detected", es: "detectó", category: "past" },
    { en: "arrived", es: "llegó", category: "past" },
    { en: "departed", es: "partió", category: "past" },
    { en: "unlocked", es: "desbloqueó", category: "past" },
    { en: "solved", es: "resolvió", category: "past" },
    { en: "calibrated", es: "calibró", category: "past" },
    { en: "recorded", es: "grabó / registró", category: "past" },
    { en: "explored", es: "exploró", category: "past" },
    { en: "yesterday", es: "ayer", category: "time" },
    { en: "last night", es: "anoche", category: "time" },
    { en: "mission", es: "misión", category: "general" },
    { en: "expedition", es: "expedición", category: "general" },
    { en: "logbook", es: "cuaderno de bitácora", category: "objects" },
    { en: "voyage", es: "travesía", category: "general" },
    { en: "milestone", es: "hito", category: "general" },
    { en: "history", es: "historia", category: "general" },
    { en: "chronicle", es: "crónica", category: "general" },
    { en: "memory", es: "recuerdo", category: "personal" }
  ],
  14: [
    { en: "graduation", es: "graduación", category: "celebration" },
    { en: "commander", es: "comandante", category: "people" },
    { en: "cadet", es: "cadete", category: "people" },
    { en: "honors", es: "honores", category: "celebration" },
    { en: "certificate", es: "certificado", category: "objects" },
    { en: "mission", es: "misión", category: "general" },
    { en: "victory", es: "victoria", category: "celebration" },
    { en: "celebration", es: "celebración", category: "celebration" },
    { en: "achievement", es: "logro", category: "celebration" },
    { en: "starbase", es: "base estelar", category: "places" },
    { en: "alliance", es: "alianza", category: "people" },
    { en: "future", es: "futuro", category: "time" },
    { en: "universe", es: "universo", category: "space" },
    { en: "journey", es: "viaje", category: "general" },
    { en: "stellar", es: "estelar", category: "adjectives" },
    { en: "honor", es: "honor", category: "general" },
    { en: "badge", es: "insignia", category: "objects" },
    { en: "diploma", es: "diploma", category: "objects" },
    { en: "legacy", es: "legado", category: "general" },
    { en: "tribute", es: "homenaje", category: "celebration" },
    { en: "outpost", es: "puesto de avanzada", category: "places" },
    { en: "galaxy", es: "galaxia", category: "space" },
    { en: "pioneer", es: "pionero", category: "people" },
    { en: "leader", es: "líder", category: "people" },
    { en: "legend", es: "leyenda", category: "general" }
  ]
};

export const MISSION_BRIEFINGS = {
  1: {
    grammar: "Verb To Be (am/is/are), Preferences (like/favorite), Abilities (can)",
    vocabulary: CURRICULUM_VOCABULARY_DATA[1],
    objective: "Presentarte ante la tripulación estelar: comparte tu nombre, edad, país de origen, tus preferencias y tus habilidades clave."
  },
  2: {
    grammar: "There is / There are (singular vs plural, articles a / an)",
    vocabulary: CURRICULUM_VOCABULARY_DATA[2],
    objective: "Explorar la base Basescrib: recorre los módulos de estudio y la cabina espacial para identificar objetos y suministros."
  },
  3: {
    grammar: "Present Simple (Routines, He/She/It + verb + s/es)",
    vocabulary: CURRICULUM_VOCABULARY_DATA[3],
    objective: "Inspeccionar rutinas de la tripulación en Base ONE: descubre qué hacen los tripulantes cada día y organiza tu horario espacial."
  },
  4: {
    grammar: "Present Continuous (Actions right now, am/is/are + verb-ing)",
    vocabulary: CURRICULUM_VOCABULARY_DATA[4],
    objective: "Diagnosticar operaciones en curso: reporta qué sistemas y tripulantes están activos durante la alerta de mantenimiento."
  },
  5: {
    grammar: "Adverbs of Frequency (always, usually, sometimes, rarely, never)",
    vocabulary: CURRICULUM_VOCABULARY_DATA[5],
    objective: "Evaluar los protocolos de seguridad de la estación: analiza la frecuencia con la que se ejecutan los mantenimientos críticos."
  },
  6: {
    grammar: "Have / Has (Possessions, equipment, tools)",
    vocabulary: CURRICULUM_VOCABULARY_DATA[6],
    objective: "Inventario del hangar técnico: verifica qué herramientas y suministros tienen los tripulantes para la próxima expedición."
  },
  7: {
    grammar: "Wh- Questions (What, Where, When, Who, Why, How)",
    vocabulary: CURRICULUM_VOCABULARY_DATA[7],
    objective: "Interrogar las señales de radio anómalas: formula preguntas precisas para descubrir el origen del mensaje del espacio profundo."
  },
  8: {
    grammar: "Possessive Adjectives & Pronouns (my/mine, your/yours, his, her/hers)",
    vocabulary: CURRICULUM_VOCABULARY_DATA[8],
    objective: "Clasificar las credenciales y equipo personal: identifica las pertenencias de cada cadete en los casilleros de la nave."
  },
  9: {
    grammar: "Object Pronouns (me, you, him, her, it, us, them) & Communication",
    vocabulary: CURRICULUM_VOCABULARY_DATA[9],
    objective: "Transmitir órdenes a las naves aliadas: envía coordenadas e instrucciones claras usando los canales de radio galácticos."
  },
  10: {
    grammar: "Demonstratives (This / That / These / Those) & Panel Controls",
    vocabulary: CURRICULUM_VOCABULARY_DATA[10],
    objective: "Operar la consola central de mando: señala y activa los interruptores, palancas y pantallas correctas de la nave."
  },
  11: {
    grammar: "Comparatives (-er / more than), Speed and Propulsion",
    vocabulary: CURRICULUM_VOCABULARY_DATA[11],
    objective: "Comparar sistemas de propulsión y astronaves: evalúa el rendimiento y especificaciones de vuelo."
  },
  12: {
    grammar: "Superlatives (-est / most), Galactic Wonders and Records",
    vocabulary: CURRICULUM_VOCABULARY_DATA[12],
    objective: "Investigar los fenómenos cósmicos más extremos de la galaxia: documenta récords y maravillas estelares."
  },
  13: {
    grammar: "Past Simple (Regular & Irregular verbs, Time Expressions: yesterday, last night)",
    vocabulary: CURRICULUM_VOCABULARY_DATA[13],
    objective: "Completar el cuaderno de bitácora histórico de expedición: documenta los hitos y descubrimientos del viaje."
  },
  14: {
    grammar: "Present Perfect & Final Graduation Review (Achievements, Milestones)",
    vocabulary: CURRICULUM_VOCABULARY_DATA[14],
    objective: "Ceremonia de graduación estelar en Basescrib: pronuncia tu discurso final y recibe las insignias de comandante."
  }
};
